# Generated by Django 3.2.8 on 2021-10-05 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='question',
            table='polls_project_question',
        ),
    ]
